# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Announcement.create(ann_title: "First Announcement", ann_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Announcement.create(ann_title: "Second Announcement", ann_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Announcement.create(ann_title: "Third Announcement", ann_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Announcement.create(ann_title: "Fourth Announcement", ann_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Announcement.create(ann_title: "Fifth Announcement", ann_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Announcement.create(ann_title: "Sixth Announcement", ann_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Announcement.create(ann_title: "Seventh Announcement", ann_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Announcement.create(ann_title: "Eighth Announcement", ann_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Announcement.create(ann_title: "Ninth Announcement", ann_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Announcement.create(ann_title: "Tenth Announcement", ann_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Announcement.create(ann_title: "Eleventh Announcement", ann_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Announcement.create(ann_title: "Twelfth Announcement", ann_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Blog.create( blog_title: "First Blog", blog_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Blog.create( blog_title: "Second Blog", blog_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Blog.create( blog_title: "Third Blog", blog_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Blog.create( blog_title: "Fourth Blog", blog_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Blog.create( blog_title: "Fifth Blog", blog_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Blog.create( blog_title: "Sixth Blog", blog_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Blog.create( blog_title: "Seventh Blog", blog_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Blog.create( blog_title: "Eighth Blog", blog_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Blog.create( blog_title: "Ninth Blog", blog_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Blog.create( blog_title: "Tenth Blog", blog_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Blog.create( blog_title: "Eleventh Blog", blog_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
Blog.create( blog_title: "Twelfth Blog", blog_body: "Bushwick Neutra messenger bag PBR, aesthetic scenester narwhal Pinterest. Twee +1 flannel jean shorts Marfa, vinyl paleo literally Portland. Tofu bespoke lo-fi meggings roof party, +1 art party Pitchfork. Viral Intelligentsia crucifix, before they sold out keffiyeh meggings ennui drinking vinegar DIY. 90's Odd Future fap, biodiesel meggings disrupt gluten-free High Life umami tote bag normcore. Artisan health goth chia disrupt Wes Anderson, tousled High Life mlkshk flannel. Vice craft beer Etsy, tattooed ethical scenester tofu shabby chic wolf blog.", image: "default.png")
